// Mock UMKM data untuk development
const mockUMKMs = [
  {
    _id: "1",
    name: "Warung Makan Sederhana",
    category: "FnB",
    description: "Restoran masakan tradisional Indonesia",
    location: {
      type: "Point",
      coordinates: [106.827, -6.1753], // Jakarta
    },
    address: "Jl. Merdeka No. 123",
    city: "Jakarta",
    province: "DKI Jakarta",
    phone: "021-1234567",
    whatsapp: "628123456789",
    website: "https://warungmakan.com",
    owner: "Ibu Siti",
    rating: 4.5,
    reviews: 128,
  },
  {
    _id: "2",
    name: "Bengkel Mobil Jaya",
    category: "Otomotif",
    description: "Bengkel servis dan perbaikan mobil profesional",
    location: {
      type: "Point",
      coordinates: [106.836, -6.185],
    },
    address: "Jl. Sudirman No. 456",
    city: "Jakarta",
    province: "DKI Jakarta",
    phone: "021-9876543",
    whatsapp: "628987654321",
    website: "https://bengkeljaya.com",
    owner: "Pak Hendra",
    rating: 4.8,
    reviews: 256,
  },
  {
    _id: "3",
    name: "Toko Elektronik Maju",
    category: "Teknologi",
    description: "Toko penjualan dan service elektronik",
    location: {
      type: "Point",
      coordinates: [106.818, -6.165],
    },
    address: "Jl. Ahmad Yani No. 789",
    city: "Jakarta",
    province: "DKI Jakarta",
    phone: "021-5555555",
    whatsapp: "628555555555",
    website: "https://tokoelektronik.com",
    owner: "Budi Santoso",
    rating: 4.3,
    reviews: 89,
  },
  {
    _id: "4",
    name: "Toko Fashion Cantik",
    category: "Fashion",
    description: "Toko fashion dan pakaian modern",
    location: {
      type: "Point",
      coordinates: [112.7515, -7.2575], // Surabaya
    },
    address: "Jl. Diponegoro No. 100",
    city: "Surabaya",
    province: "Jawa Timur",
    phone: "031-1234567",
    whatsapp: "628912345678",
    website: "https://fashioncantik.com",
    owner: "Nina Putri",
    rating: 4.6,
    reviews: 145,
  },
  {
    _id: "5",
    name: "Kerajinan Batik Nusantara",
    category: "Kerajinan",
    description: "Pengrajin batik tradisional Indonesia",
    location: {
      type: "Point",
      coordinates: [110.4064, -7.5505], // Yogyakarta
    },
    address: "Jl. Malioboro No. 999",
    city: "Yogyakarta",
    province: "DI Yogyakarta",
    phone: "0274-1234567",
    whatsapp: "6281234567890",
    website: "https://batiknusantara.com",
    owner: "Slamet Riyanto",
    rating: 4.9,
    reviews: 312,
  },
  {
    _id: "6",
    name: "Kedai Kopi Nusantara",
    category: "FnB",
    description: "Kopi tradisional & camilan lokal",
    location: {
      type: "Point",
      coordinates: [107.615, -6.914744],
    },
    address: "Jl. Braga No. 45",
    city: "Bandung",
    province: "Jawa Barat",
    phone: "022-7654321",
    whatsapp: "628211234567",
    website: "https://kedaikopinusantara.id",
    owner: "Pak Arman",
    rating: 4.6,
    reviews: 342,
  },
  {
    _id: "7",
    name: "Bakmi Pak Budi",
    category: "FnB",
    description: "Bakmi ayam resep keluarga",
    location: {
      type: "Point",
      coordinates: [112.752088, -7.257472],
    },
    address: "Jl. Gubeng No. 88",
    city: "Surabaya",
    province: "Jawa Timur",
    phone: "031-9876543",
    whatsapp: "628219876543",
    website: "http://bakmipakbudi.com",
    owner: "Budi Santoso",
    rating: 4.2,
    reviews: 210,
  },
  {
    _id: "8",
    name: "Sari Rasa Catering",
    category: "FnB",
    description: "Catering prasmanan untuk acara kecil hingga besar",
    location: {
      type: "Point",
      coordinates: [110.369487, -7.79558],
    },
    address: "Jl. Malioboro No. 12",
    city: "Yogyakarta",
    province: "DI Yogyakarta",
    phone: "0274-334455",
    whatsapp: "628123334455",
    website: "https://sarirasa-catering.id",
    owner: "Ibu Rina",
    rating: 4.7,
    reviews: 175,
  },
  {
    _id: "9",
    name: "Warung Soto Makmur",
    category: "FnB",
    description: "Soto tradisional dengan kuah rempah khas",
    location: {
      type: "Point",
      coordinates: [110.426, -7.009],
    },
    address: "Jl. Pemuda No. 7",
    city: "Semarang",
    province: "Jawa Tengah",
    phone: "024-556677",
    whatsapp: "628155667788",
    website: "http://warungsotomakmur.id",
    owner: "Slamet",
    rating: 4.3,
    reviews: 98,
  },
  {
    _id: "10",
    name: "Dapur Bali",
    category: "FnB",
    description: "Masakan Bali autentik dan seafood segar",
    location: {
      type: "Point",
      coordinates: [115.216667, -8.65],
    },
    address: "Jl. Raya Kuta No. 9",
    city: "Denpasar",
    province: "Bali",
    phone: "0361-778899",
    whatsapp: "628177889900",
    website: "https://dapur-bali.co.id",
    owner: "Ni Luh",
    rating: 4.8,
    reviews: 456,
  },
  {
    _id: "11",
    name: "Kedai Roti Manis",
    category: "FnB",
    description: "Roti panggang dan pastry harian",
    location: {
      type: "Point",
      coordinates: [98.674, 3.589],
    },
    address: "Jl. Merdeka No. 5",
    city: "Medan",
    province: "Sumatera Utara",
    phone: "061-445566",
    whatsapp: "628144556677",
    website: "http://rotimanis-medan.id",
    owner: "Ani",
    rating: 4.1,
    reviews: 64,
  },
  {
    _id: "12",
    name: "Seafood Makassar",
    category: "FnB",
    description: "Seafood bakar & sup ikan khas Makassar",
    location: {
      type: "Point",
      coordinates: [119.416, -5.147],
    },
    address: "Jl. Losari No. 3",
    city: "Makassar",
    province: "Sulawesi Selatan",
    phone: "0411-223344",
    whatsapp: "628122334455",
    website: "https://seafoodmakassar.com",
    owner: "Haji Amir",
    rating: 4.4,
    reviews: 290,
  },
  {
    _id: "13",
    name: "Gudeg Bu Lestari",
    category: "FnB",
    description: "Gudeg manis tradisional, buka tiap pagi",
    location: {
      type: "Point",
      coordinates: [110.367, -7.807],
    },
    address: "Jl. Kaliurang No. 21",
    city: "Yogyakarta",
    province: "DI Yogyakarta",
    phone: "0274-556611",
    whatsapp: "628155661122",
    website: "http://gudegbulestari.co.id",
    owner: "Lestari",
    rating: 4.5,
    reviews: 134,
  },
  {
    _id: "14",
    name: "Nasi Goreng Cemara",
    category: "FnB",
    description: "Nasi goreng spesial dengan bumbu rahasia",
    location: {
      type: "Point",
      coordinates: [114.588, -3.315],
    },
    address: "Jl. Sultan Adam No. 10",
    city: "Banjarmasin",
    province: "Kalimantan Selatan",
    phone: "0511-334455",
    whatsapp: "628133445566",
    website: "https://nasigorengcemara.id",
    owner: "Heba",
    rating: 4.0,
    reviews: 52,
  },
  {
    _id: "15",
    name: "Rumah Makan Manado",
    category: "FnB",
    description: "Masakan Manado pedas dan segar",
    location: {
      type: "Point",
      coordinates: [124.827, 1.482],
    },
    address: "Jl. Sam Ratulangi No. 2",
    city: "Manado",
    province: "Sulawesi Utara",
    phone: "0431-778800",
    whatsapp: "628177880011",
    website: "http://rumahmakan-manado.com",
    owner: "Pak Dodo",
    rating: 4.6,
    reviews: 198,
  },
  {
    _id: "16",
    name: "Pempek Palembang Asli",
    category: "FnB",
    description: "Pempek kapal selam dan empek-empek otentik",
    location: {
      type: "Point",
      coordinates: [104.745, -2.976],
    },
    address: "Jl. Sudirman No. 77",
    city: "Palembang",
    province: "Sumatera Selatan",
    phone: "0711-998877",
    whatsapp: "628199887766",
    website: "https://pempekpalembang.id",
    owner: "Pak Hendra",
    rating: 4.3,
    reviews: 221,
  },
  {
    _id: "17",
    name: "Bakso Balikpapan",
    category: "FnB",
    description: "Bakso urat dan bakso goreng khas Balikpapan",
    location: {
      type: "Point",
      coordinates: [116.881, -1.267],
    },
    address: "Jl. MT Haryono No. 54",
    city: "Balikpapan",
    province: "Kalimantan Timur",
    phone: "0542-887766",
    whatsapp: "628288776655",
    website: "http://baksobalikpapan.com",
    owner: "Ibu Sari",
    rating: 4.2,
    reviews: 83,
  },
  {
    _id: "18",
    name: "Toko Kue Kupang",
    category: "FnB",
    description: "Kue tradisional dan kue ulang tahun",
    location: {
      type: "Point",
      coordinates: [123.579, -10.177],
    },
    address: "Jl. Jend. Sudirman No. 1",
    city: "Kupang",
    province: "Nusa Tenggara Timur",
    phone: "0380-223344",
    whatsapp: "628122334477",
    website: "https://tokokuekupang.id",
    owner: "Martha",
    rating: 4.0,
    reviews: 39,
  },
  {
    _id: "19",
    name: "Warung Soto Pontianak",
    category: "FnB",
    description: "Soto ayam khas Kalimantan Barat",
    location: {
      type: "Point",
      coordinates: [109.339, -0.025],
    },
    address: "Jl. Gajah Mada No. 15",
    city: "Pontianak",
    province: "Kalimantan Barat",
    phone: "0561-445566",
    whatsapp: "628144556600",
    website: "http://warungsotopntk.id",
    owner: "Rudi",
    rating: 4.1,
    reviews: 58,
  },
  {
    _id: "20",
    name: "Lesehan Pak Agus",
    category: "FnB",
    description: "Lesehan seafood & lauk pauk rumah",
    location: {
      type: "Point",
      coordinates: [101.449, 0.507],
    },
    address: "Jl. Riau No. 20",
    city: "Pekanbaru",
    province: "Riau",
    phone: "0761-667788",
    whatsapp: "628166778899",
    website: "https://lesehanpakagus.id",
    owner: "Agus Setiawan",
    rating: 4.2,
    reviews: 71,
  },
  {
    _id: "21",
    name: "Bengkel Motor Sentosa",
    category: "Otomotif",
    description: "Servis motor & ganti oli cepat",
    location: { type: "Point", coordinates: [106.828, -6.176] },
    address: "Jl. Karet No. 12",
    city: "Jakarta",
    province: "DKI Jakarta",
    phone: "021-3344556",
    whatsapp: "628133445566",
    website: "https://bengkelmotorsentosa.id",
    owner: "Slamet",
    rating: 4.1,
    reviews: 48,
  },
  {
    _id: "22",
    name: "AutoCare Surabaya",
    category: "Otomotif",
    description: "Perawatan mobil lengkap dan cuci mobil",
    location: { type: "Point", coordinates: [112.739, -7.273] },
    address: "Jl. Merdeka No. 2",
    city: "Surabaya",
    province: "Jawa Timur",
    phone: "031-223344",
    whatsapp: "628122334455",
    website: "http://autocaresby.com",
    owner: "Dwi",
    rating: 4.4,
    reviews: 92,
  },
  {
    _id: "23",
    name: "Bengkel Sinar Motor",
    category: "Otomotif",
    description: "Sparepart & reparasi mesin",
    location: { type: "Point", coordinates: [110.369, -7.803] },
    address: "Jl. Gejayan No. 5",
    city: "Yogyakarta",
    province: "DI Yogyakarta",
    phone: "0274-778899",
    whatsapp: "628177889977",
    website: "https://sinarmotorjogja.id",
    owner: "Eko",
    rating: 4.5,
    reviews: 64,
  },
  {
    _id: "24",
    name: "Speedy Garage",
    category: "Otomotif",
    description: "Tune-up dan service AC mobil",
    location: { type: "Point", coordinates: [110.414, -7.009] },
    address: "Jl. MT Haryono No. 10",
    city: "Semarang",
    province: "Jawa Tengah",
    phone: "024-998877",
    whatsapp: "628199887766",
    website: "http://speedygarage.co.id",
    owner: "Fajar",
    rating: 4.2,
    reviews: 37,
  },
  {
    _id: "25",
    name: "Oto Klinik Medan",
    category: "Otomotif",
    description: "Perbaikan bodi dan pengecatan mobil",
    location: { type: "Point", coordinates: [98.672, 3.59] },
    address: "Jl. Pattimura No. 8",
    city: "Medan",
    province: "Sumatera Utara",
    phone: "061-998877",
    whatsapp: "628199887700",
    website: "https://otoklinikmedan.id",
    owner: "Hendra",
    rating: 4.0,
    reviews: 44,
  },
  {
    _id: "26",
    name: "Bengkel Prima Makassar",
    category: "Otomotif",
    description: "Servis ringan & parts resmi",
    location: { type: "Point", coordinates: [119.408, -5.147] },
    address: "Jl. Sultan Alauddin No. 20",
    city: "Makassar",
    province: "Sulawesi Selatan",
    phone: "0411-665544",
    whatsapp: "628166554433",
    website: "https://bengkelprimamks.id",
    owner: "Rian",
    rating: 4.3,
    reviews: 58,
  },
  {
    _id: "27",
    name: "AutoFix Balikpapan",
    category: "Otomotif",
    description: "Mekanik berpengalaman untuk semua kendaraan",
    location: { type: "Point", coordinates: [116.845, -1.278] },
    address: "Jl. Sudirman No. 4",
    city: "Balikpapan",
    province: "Kalimantan Timur",
    phone: "0542-667788",
    whatsapp: "628266778899",
    website: "http://autofixbalikpapan.com",
    owner: "Andi",
    rating: 4.1,
    reviews: 26,
  },
  {
    _id: "28",
    name: "Bengkel Serba Bisa Pontianak",
    category: "Otomotif",
    description: "Service, ganti oli, dan tune-up cepat",
    location: { type: "Point", coordinates: [109.34, -0.03] },
    address: "Jl. Gajah Mada No. 45",
    city: "Pontianak",
    province: "Kalimantan Barat",
    phone: "0561-778899",
    whatsapp: "628177889900",
    website: "https://bengkelsbbkntk.id",
    owner: "Susi",
    rating: 4.0,
    reviews: 31,
  },
  {
    _id: "29",
    name: "Mekanik Jaya Pekanbaru",
    category: "Otomotif",
    description: "Ahli rem & suspensi",
    location: { type: "Point", coordinates: [101.45, 0.506] },
    address: "Jl. Riau No. 9",
    city: "Pekanbaru",
    province: "Riau",
    phone: "0761-556677",
    whatsapp: "628155667700",
    website: "http://mekanikjayapku.id",
    owner: "Tono",
    rating: 4.2,
    reviews: 22,
  },
  {
    _id: "30",
    name: "Bengkel Cepat Kupang",
    category: "Otomotif",
    description: "Service motor & ganti sparepart",
    location: { type: "Point", coordinates: [123.58, -10.18] },
    address: "Jl. El Tari No. 3",
    city: "Kupang",
    province: "Nusa Tenggara Timur",
    phone: "0380-334455",
    whatsapp: "628033445566",
    website: "https://bengkelkupang.id",
    owner: "Rudi",
    rating: 4.0,
    reviews: 14,
  },
  {
    _id: "31",
    name: "IT Solutions Jakarta",
    category: "Teknologi",
    description: "Jasa instalasi jaringan dan IT support",
    location: { type: "Point", coordinates: [106.82, -6.17] },
    address: "Jl. Thamrin No. 66",
    city: "Jakarta",
    province: "DKI Jakarta",
    phone: "021-66778899",
    whatsapp: "628166778899",
    website: "https://itsolutionsjakarta.id",
    owner: "Rico",
    rating: 4.4,
    reviews: 77,
  },
  {
    _id: "32",
    name: "Toko Gadget Surabaya",
    category: "Teknologi",
    description: "Smartphone & aksesoris resmi",
    location: { type: "Point", coordinates: [112.744, -7.26] },
    address: "Jl. Tunjungan No. 1",
    city: "Surabaya",
    province: "Jawa Timur",
    phone: "031-776655",
    whatsapp: "628177665544",
    website: "http://tokogadgetsby.com",
    owner: "Maya",
    rating: 4.3,
    reviews: 66,
  },
  {
    _id: "33",
    name: "Service Komputer Jogja",
    category: "Teknologi",
    description: "Perbaikan PC, laptop & data recovery",
    location: { type: "Point", coordinates: [110.369, -7.79] },
    address: "Jl. Kaliurang No. 77",
    city: "Yogyakarta",
    province: "DI Yogyakarta",
    phone: "0274-445566",
    whatsapp: "628144556677",
    website: "https://servicekomputerjogja.id",
    owner: "Dina",
    rating: 4.5,
    reviews: 58,
  },
  {
    _id: "34",
    name: "WebDev Semarang",
    category: "Teknologi",
    description: "Jasa pembuatan website & e-commerce",
    location: { type: "Point", coordinates: [110.42, -7.01] },
    address: "Jl. Pandanaran No. 10",
    city: "Semarang",
    province: "Jawa Tengah",
    phone: "024-334455",
    whatsapp: "628133445500",
    website: "http://webdevsemarang.com",
    owner: "Fadia",
    rating: 4.6,
    reviews: 41,
  },
  {
    _id: "35",
    name: "IT Mart Medan",
    category: "Teknologi",
    description: "Komputer desktop & server solutions",
    location: { type: "Point", coordinates: [98.675, 3.59] },
    address: "Jl. Imam Bonjol No. 22",
    city: "Medan",
    province: "Sumatera Utara",
    phone: "061-778899",
    whatsapp: "628177889911",
    website: "https://itmartmedan.id",
    owner: "Anton",
    rating: 4.2,
    reviews: 33,
  },
  {
    _id: "36",
    name: "DevOps Makassar",
    category: "Teknologi",
    description: "Cloud & DevOps consulting",
    location: { type: "Point", coordinates: [119.428, -5.15] },
    address: "Jl. Andi Pangeran No. 6",
    city: "Makassar",
    province: "Sulawesi Selatan",
    phone: "0411-889977",
    whatsapp: "628188997766",
    website: "https://devopsmakassar.id",
    owner: "Riza",
    rating: 4.7,
    reviews: 19,
  },
  {
    _id: "37",
    name: "Fashionista Shop",
    category: "Fashion",
    description: "Pakaian kasual & aksesoris trendi",
    location: { type: "Point", coordinates: [106.83, -6.17] },
    address: "Jl. Senopati No. 21",
    city: "Jakarta",
    province: "DKI Jakarta",
    phone: "021-3344778",
    whatsapp: "628133447788",
    website: "https://fashionista.id",
    owner: "Nadia",
    rating: 4.5,
    reviews: 124,
  },
  {
    _id: "38",
    name: "Butik Surabaya Elegan",
    category: "Fashion",
    description: "Busana formal dan designer lokal",
    location: { type: "Point", coordinates: [112.75, -7.25] },
    address: "Jl. Rungkut No. 8",
    city: "Surabaya",
    province: "Jawa Timur",
    phone: "031-667799",
    whatsapp: "628166779900",
    website: "http://butikelegan.com",
    owner: "Wina",
    rating: 4.6,
    reviews: 88,
  },
  {
    _id: "39",
    name: "Fashion Corner Jogja",
    category: "Fashion",
    description: "Pakaian batik modern dan kain lokal",
    location: { type: "Point", coordinates: [110.366, -7.803] },
    address: "Jl. Sosrowijayan No. 3",
    city: "Yogyakarta",
    province: "DI Yogyakarta",
    phone: "0274-998800",
    whatsapp: "628199880011",
    website: "https://fashioncornerjogja.id",
    owner: "Ayu",
    rating: 4.4,
    reviews: 52,
  },
  {
    _id: "40",
    name: "Pusat Fashion Semarang",
    category: "Fashion",
    description: "Outlet pakaian keluarga dan anak-anak",
    location: { type: "Point", coordinates: [110.42, -7.01] },
    address: "Jl. Gajah No. 11",
    city: "Semarang",
    province: "Jawa Tengah",
    phone: "024-776655",
    whatsapp: "628177665544",
    website: "http://pusatfashionsmg.com",
    owner: "Rima",
    rating: 4.1,
    reviews: 29,
  },
  {
    _id: "41",
    name: "Butik Medan",
    category: "Fashion",
    description: "Pakaian tradisional dan modern",
    location: { type: "Point", coordinates: [98.675, 3.59] },
    address: "Jl. Merdeka No. 20",
    city: "Medan",
    province: "Sumatera Utara",
    phone: "061-667700",
    whatsapp: "628166770011",
    website: "https://butikmedan.id",
    owner: "Lila",
    rating: 4.0,
    reviews: 21,
  },
  {
    _id: "42",
    name: "Fashion Bali Collection",
    category: "Fashion",
    description: "Resort wear & pakaian pantai",
    location: { type: "Point", coordinates: [115.215, -8.65] },
    address: "Jl. Legian No. 14",
    city: "Denpasar",
    province: "Bali",
    phone: "0361-334455",
    whatsapp: "628133445577",
    website: "http://fashionbalicollection.com",
    owner: "Made",
    rating: 4.7,
    reviews: 67,
  },
  {
    _id: "43",
    name: "Toko Kerajinan Solo",
    category: "Kerajinan",
    description: "Kerajinan kayu & oleh-oleh khas Solo",
    location: { type: "Point", coordinates: [110.8, -7.57] },
    address: "Jl. Slamet Riyadi No. 9",
    city: "Solo",
    province: "Jawa Tengah",
    phone: "0271-334455",
    whatsapp: "628133445588",
    website: "https://kerajinan-solo.id",
    owner: "Ibu Ratna",
    rating: 4.8,
    reviews: 102,
  },
  {
    _id: "44",
    name: "Pengrajin Rotan Pekanbaru",
    category: "Kerajinan",
    description: "Furniture rotan handmade",
    location: { type: "Point", coordinates: [101.45, 0.5] },
    address: "Jl. Sudirman No. 55",
    city: "Pekanbaru",
    province: "Riau",
    phone: "0761-334411",
    whatsapp: "628133441122",
    website: "http://rotanpekanbaru.com",
    owner: "Hadi",
    rating: 4.2,
    reviews: 38,
  },
  {
    _id: "45",
    name: "Kerajinan Tangan Bali",
    category: "Kerajinan",
    description: "Aksesori & seni ukir khas Bali",
    location: { type: "Point", coordinates: [115.211, -8.68] },
    address: "Jl. Ubud No. 2",
    city: "Gianyar",
    province: "Bali",
    phone: "0361-445500",
    whatsapp: "628144550011",
    website: "https://kerajinbali.id",
    owner: "Ni Komang",
    rating: 4.6,
    reviews: 76,
  },
  {
    _id: "46",
    name: "Pengrajin Perak Yogyakarta",
    category: "Kerajinan",
    description: "Perak & perhiasan handmade",
    location: { type: "Point", coordinates: [110.369, -7.793] },
    address: "Jl. Malioboro No. 50",
    city: "Yogyakarta",
    province: "DI Yogyakarta",
    phone: "0274-667788",
    whatsapp: "628166778800",
    website: "http://perakyogya.com",
    owner: "Siti",
    rating: 4.9,
    reviews: 88,
  },
  {
    _id: "47",
    name: "Craftsman Makassar",
    category: "Kerajinan",
    description: "Kerajinan laut & anyaman lokal",
    location: { type: "Point", coordinates: [119.423, -5.147] },
    address: "Jl. Pettarani No. 7",
    city: "Makassar",
    province: "Sulawesi Selatan",
    phone: "0411-334400",
    whatsapp: "628133440011",
    website: "https://craftsmakassar.id",
    owner: "Yusuf",
    rating: 4.1,
    reviews: 27,
  },
  {
    _id: "48",
    name: "Kerajinan Timor Kupang",
    category: "Kerajinan",
    description: "Tenun & kerajinan khas NTT",
    location: { type: "Point", coordinates: [123.58, -10.18] },
    address: "Jl. El Tari No. 10",
    city: "Kupang",
    province: "Nusa Tenggara Timur",
    phone: "0380-667700",
    whatsapp: "628066770011",
    website: "https://kerajinankupang.id",
    owner: "Meri",
    rating: 4.3,
    reviews: 16,
  },
  {
    _id: "49",
    name: "Gallery Keramik Medan",
    category: "Kerajinan",
    description: "Keramik & cinderamata unik",
    location: { type: "Point", coordinates: [98.675, 3.587] },
    address: "Jl. Sisingamangaraja No. 33",
    city: "Medan",
    province: "Sumatera Utara",
    phone: "061-334477",
    whatsapp: "628133447700",
    website: "http://gallerykeramikmedan.com",
    owner: "Rani",
    rating: 4.0,
    reviews: 12,
  },
  {
    _id: "50",
    name: "Studio Kreatif Pontianak",
    category: "Kerajinan",
    description: "Desain & produksi souvenir lokal",
    location: { type: "Point", coordinates: [109.34, -0.02] },
    address: "Jl. Gajah Mada No. 88",
    city: "Pontianak",
    province: "Kalimantan Barat",
    phone: "0561-778800",
    whatsapp: "628177880022",
    website: "https://studiokreatifptk.id",
    owner: "Indra",
    rating: 4.2,
    reviews: 20,
  },
];

// Filter mock data
function filterMockData(category, city, search) {
  let filtered = mockUMKMs;

  if (category && category !== "Semua") {
    filtered = filtered.filter((u) => u.category === category);
  }
  if (city) {
    filtered = filtered.filter((u) =>
      u.city.toLowerCase().includes(city.toLowerCase()),
    );
  }
  if (search) {
    const searchLower = search.toLowerCase();
    filtered = filtered.filter(
      (u) =>
        u.name.toLowerCase().includes(searchLower) ||
        u.description.toLowerCase().includes(searchLower),
    );
  }

  return filtered;
}

export { mockUMKMs, filterMockData };
